### PR TITLE
Add CI to RoboRacing

### LINKED ISSUE #31: Create CI for RoboRacing
This is mostly an issue to remind me to do this. 

I'll be working on this on the CI branch.

### PR DESCRIPTION
**Pull request by jgkamat**
CI is set up except for dependencies, I need someone to help me work through those.

Currently, I'm getting this error: https://4-15688257-gh.circle-artifacts.com/0/tmp/circle-artifacts.TPGVB0z/compile.txt

Can you give me a command to run to fix it? I don't know how to ros.

Closes #31

### CODE REVIEW

**Comment by jgkamat** [comment]
Scratch that, I think there's an issue with my provisioning. When I run your setup command, I get this:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rr_platform: Cannot locate rosdep definition for [uvc_camera]
iarrc: Cannot locate rosdep definition for [uvc_camera]
avc: Cannot locate rosdep definition for [uvc_camera]
Warning: running 'rosdep update' as root is not recommended.
  You should run 'sudo rosdep fix-permissions' and invoke 'rosdep update' again without sudo.
```
Any ideas?

**Comment by barulicm** [comment]
Put the following above your call to `rosdep install`
```
sudo rosdep init
rosdep update
```

and get rid of the `rosdep update` call after `rosdep install`.

**Comment by jgkamat** [comment]
I seem to still be getting that error. I think it might be easier to meet up with you or another RR member to debug this...

**Comment by jgkamat** [comment]
Just to be sure, you guys are using ROS kinetic right? I'm getting this same error when installing inside the igvc ROS image, so I'm not sure what the problem could be.

**Comment by barulicm** [comment]
Upon further investigation and upgrading my own machine to 16.04, it seems the uvc_camera package hasn't been upgraded to ROS Kinetic.

I'm looking into replacements. Until then, I'll temporarily remove the dependency from our package description that causes this issue. I'll double check on my linux machine later today to make sure there aren't any other missing dependencies in ROS Kinetic.

**Comment by jgkamat** [comment]
According to [this website](http://wiki.ros.org/uvc_camera) uvc_camera is deprecated in favor of [libusb_camera](http://wiki.ros.org/libuvc_camera), but I'm not sure if it's on kinetic yet either (it dosen't seem to have a kinetic tab on that page.

**Comment by barulicm** [comment]
Yeah, and IGVC is using the usb_cam package, but that's not in Kinetic either. It looks like there aren't any USB camera packages officially in Kinetic yet.

**Comment by barulicm** [comment]
I've temporarily removed the uvc_camera dependency on master. You should now be able to run the rosdep install command without issue.

**Comment by jgkamat** [comment]
I had to add a few other dependencies, but I think this is good to go now! [I'm not sure if tests are working correctly, does this output look correct to you?](https://10-15688257-gh.circle-artifacts.com/0/tmp/circle-artifacts.KKK9RO3/tests.txt). Other than that, I think this is good to go!

**Comment by barulicm** [comment]
Yeah, that's the correct output because we don't actually have any tests setup for RR yet.

**Comment by barulicm** [comment]
Also, the PCL dependency makes sense. That just hadn't been added to the dependency list yet. 
Do you know which target needed libusb installed?

**Comment by jgkamat** [comment]
This is the error I get w/o libusb-dev:
```
-- ==> add_subdirectory(rr_platform)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at /opt/ros/kinetic/share/sick_tim/cmake/sick_timConfig.cmake:106 (message):
  Project 'sick_tim' specifies '/usr/include/libusb-1.0' as an include dir,
  which is not found.  It does neither exist as an absolute directory nor in
  '/opt/ros/kinetic//usr/include/libusb-1.0'.  Ask the maintainer 'Martin
  Günther <martin.guenther@dfki.de>' to fix it.
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  rr_platform/CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/build/CMakeFiles/CMakeOutput.log".
See also "/root/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```

Probably a missing dependency from the sick_tim package. This image is the lightest image that ubuntu provides, so it's missing a lot of commonly installed things.

**Comment by jgkamat** [comment]
Interestingly `sick_tim` actually does seem to have this dependency added: https://github.com/uos/sick_tim/commit/011fc01d890e3ca7727dcde261b9222ef17f05fc

I'm not sure why it wasn't installed...

**Pull request merged**
